name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}, MongoDB ${{ matrix.mongodb-version }}
    strategy:
      matrix:
        ruby: ['2.7.6', '3.0.4', '3.1.2']
        mongodb-version: ['4.2', '4.4', '5.0', '6.0']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - name: Run the default task
      run: bundle exec rake
